export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const FILTER_COMPONENTS = 'FILTER_COMPONENTS';

export const ADD_CONTAINER = 'ADD_CONTAINER';
export const UPDATE_CONTAINER = 'UPDATE_CONTAINER';
export const DELETE_CONTAINER = 'DELETE_CONTAINER';
export const FILTER_CONTAINERS = 'FILTER_CONTAINERS';

export const FETCH_HOSTS = 'FETCH_HOSTS';

export const ADD_DATABASE = 'ADD_DATABASE';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const DELETE_DATABASE = 'DELETE_COMPONENT';
export const FILTER_DATABASES = 'FILTER_DATABASES';

export const SHOW_FAILURE_MESSAGE = 'FAIL_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SWITCH_VIEW = 'SWITCH_VIEW';

export const SET_ENTITY = 'SET_ENTITY';
export const CLEAR_ENTITY = 'CLEAR_ENTITY';

export const SET_MODE = 'SET_MODE';
export const CLEAR_MODE = 'CLEAR_MODE';
